[package]
name = "jellysink"
description = "Headless Jellyfin cast target that plays in MPV"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
jellysink-core.workspace = true

clap.workspace = true
color-eyre.workspace = true
dialoguer.workspace = true
futures-util.workspace = true
ico.workspace = true
image.workspace = true
ksni.workspace = true
ratatui.workspace = true
ratatui-image.workspace = true
reqwest.workspace = true
rustix.workspace = true
self_update.workspace = true
serde.workspace = true
serde_json.workspace = true
tikv-jemallocator.workspace = true
tokio = { workspace = true, features = [
    "macros",
    "process",
    "signal",
    "net",
    "io-util",
    "fs",
] }
tokio-tungstenite.workspace = true
tracing.workspace = true
uuid.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile.workspace = true
